name: CI Workflow

on: [push, pull_request]

jobs:

  # Linting with Pre-commit
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.12.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.6

      # Run pre-commit hooks (e.g., black, flake8, isort)
      - uses: pre-commit/action@v3.0.0


  # Test runs
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      # install poetry to allow cacheing
      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python 3.12.6
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.6
          cache: 'poetry'
      - name: Install Requirements
        run: |
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run Tests
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          poetry run pytest -n auto
