name: CI Workflow

on: [push]

jobs:
  # Linting with Pre-commit
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.6

      # Run pre-commit hooks (e.g., black, flake8, isort)
      - uses: pre-commit/action@v3.0.0

  # Test runs
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.18"
          enable-cache: true  # Enables built-in caching for uv

      - name: Set up Python 3.12.6
        run: uv python install 3.12.6

      # Install dependencies with all extras (including dev)
      - name: Install Requirements
        run: uv sync --extra=dev

      # Run tests with environment variables
      - name: Run Tests
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: uv run pytest -n auto
